from ds.account.models import Trophy
from ds.goals.models import SavingCategory, Saving, DS_TROPHY_AWARD
from ds.charities.models import Charity, CauseCategory
from ds.settings import MEDIA_URL

def run():
    CauseCategory.objects.create(cause_category="Animals", cause_category_image=MEDIA_URL+'img/cause_category/animals.gif')
    CauseCategory.objects.create(cause_category="Arts/Culture", cause_category_image=MEDIA_URL+'img/cause_category/arts.gif')
    CauseCategory.objects.create(cause_category="Education", cause_category_image=MEDIA_URL+'img/cause_category/education.gif')
    CauseCategory.objects.create(cause_category="Environment", cause_category_image=MEDIA_URL+'img/cause_category/environment.gif')
    CauseCategory.objects.create(cause_category="Health", cause_category_image=MEDIA_URL+'img/cause_category/health.gif')
    CauseCategory.objects.create(cause_category="Human Services", cause_category_image=MEDIA_URL+'img/cause_category/human.gif')
    CauseCategory.objects.create(cause_category="International", cause_category_image=MEDIA_URL+'img/cause_category/international.gif')
    CauseCategory.objects.create(cause_category="Public Benefit", cause_category_image=MEDIA_URL+'img/cause_category/public.gif')
    CauseCategory.objects.create(cause_category="Religion", cause_category_image=MEDIA_URL+'img/cause_category/religion.gif')
    Trophy.objects.create(award=DS_TROPHY_AWARD)
    charity = Charity(charity_name="Charity Water", city="New York", state="NY", zip="10014", impact="Clean water for one person", highlighted="No bottled water, all tap water for a month", perks="2-to-1 matching", ds_verified=True, spotlight=True, logo=MEDIA_URL+'img/charities/charity_water/charity-water-logo.png', image1=MEDIA_URL+'img/charities/charity_water/charity_water_image_1.png', website="http://www.charitywater.org")
    charity.save()
    cause = CauseCategory.objects.get(cause_category="Health")
    charity.cause_categories.add(cause)
    cause = CauseCategory.objects.get(cause_category="International")
    charity.cause_categories.add(cause)
    charity.save()
    Trophy.objects.create(award="Charity Water")
    charity = Charity(charity_name="Dartmouth College", city="Hanover", state="NH", zip="03755", impact="1 day student scholarship", highlighted="Turn down the heat when you're not home for 1 month", perks="Dartmouth rocks!", ds_verified=True, spotlight=True, logo=MEDIA_URL+'img/charities/dartmouth_college/dartmouth_college_logo.png', image1=MEDIA_URL+'img/charities/dartmouth_college/dartmouth_college_image_1.png', website="http://www.dartmouth.edu")
    charity.save()
    cause = CauseCategory.objects.get(cause_category="Education")
    charity.cause_categories.add(cause)
    charity.save()
    Trophy.objects.create(award="Dartmouth College")
    charity = Charity(charity_name="Grassroot Soccer", city="Norwich", state="VT", zip="05055", impact="Educate 100 children on AIDS", highlighted="Unregister from your gym for 1 month and run outside instead", perks="100th donor wins trip to South Africa", ds_verified=True, spotlight=True, logo=MEDIA_URL+'img/charities/grassroots_soccer/grassroots_soccer_logo.png', image1=MEDIA_URL+'img/charities/grassroots_soccer/grassroots_soccer_image_1.png', website="http://www.grassrootsoccer.org")
    charity.save()
    cause = CauseCategory.objects.get(cause_category="Health")
    charity.cause_categories.add(cause)
    cause = CauseCategory.objects.get(cause_category="International")
    charity.cause_categories.add(cause)
    charity.save()
    Trophy.objects.create(award="Grassroot Soccer")
    charity = Charity(charity_name="World Wildlife Fund", city="Washington D.C.", state="DC", zip="20090", impact="Extend tiger's life 1 years", perks="1-to-1 matching by Leo DiCaprio", ds_verified=True)
    charity.save()
    cause = CauseCategory.objects.get(cause_category="Animals")
    charity.cause_categories.add(cause)
    cause = CauseCategory.objects.get(cause_category="Environment")
    charity.cause_categories.add(cause)
    cause = CauseCategory.objects.get(cause_category="International")
    charity.cause_categories.add(cause)
    charity.save()
    Trophy.objects.create(award="World Wildlife Fund")
    SavingCategory.objects.create(saving_category="foodbev", image=MEDIA_URL+'img/foodbev.gif')
    SavingCategory.objects.create(saving_category="entertain", image=MEDIA_URL+'img/entertainment.gif')
    SavingCategory.objects.create(saving_category="shopping", image=MEDIA_URL+'img/shopping.gif')
    SavingCategory.objects.create(saving_category="tech", image=MEDIA_URL+'img/tech.gif')
    SavingCategory.objects.create(saving_category="home", image=MEDIA_URL+'img/home.gif')
    SavingCategory.objects.create(saving_category="transport", image=MEDIA_URL+'img/transport.gif')
    SavingCategory.objects.create(saving_category="gifts", image=MEDIA_URL+'img/gifts.gif')
    SavingCategory.objects.create(saving_category="finance", image=MEDIA_URL+'img/finance.gif')
    SavingCategory.objects.create(saving_category="other", image=MEDIA_URL+'img/other.gif')
    saving = Saving(saving_type="Give up Christmas", social=True, ds_suggested=True, difficulty="medium", description="Been good all year-long? Be even better for Christmas and have your friends give those ill-thought out presents to charity.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="shopping")
    saving.saving_categories.add(category)
    saving.save()
    category = SavingCategory.objects.get(saving_category="gifts")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Give up your birthday", social=True, ds_suggested=False, difficulty="medium", description="This one's been pretty high-profile recently.  Start a campaign and tell your friends to donate to a cause of your choice for your birthday, instead of giving you presents.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="shopping")
    saving.saving_categories.add(category)
    saving.save()
    category = SavingCategory.objects.get(saving_category="gifts")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Become a car-sharer", social=False, ds_suggested=True, difficulty="hard", description="Occasional car users: sell your car and sign up for Zipcar.  It's ridiculous how much cheaper it is for you.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="transport")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Flowers for V-Day", social=False, ds_suggested=False, difficulty="hard", description="Potentially scary.  You'll know whether you have the right lady for this!")
    saving.save()
    category = SavingCategory.objects.get(saving_category="shopping")
    saving.saving_categories.add(category)
    saving.save()
    category = SavingCategory.objects.get(saving_category="gifts")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Your wedding costs", social=False, ds_suggested=False, difficulty="hard", description="Find some small and ridiculously expensive item in your wedding (there are lots of them), Downsize it and donate it.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="entertain")
    saving.saving_categories.add(category)
    saving.save()
    category = SavingCategory.objects.get(saving_category="other")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Wedding gifts", social=True, ds_suggested=False, difficulty="hard", description="Registries rip you and the gift-givers off.  Give them the option of donating your gift through Downsize.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="shopping")
    saving.saving_categories.add(category)
    saving.save()
    category = SavingCategory.objects.get(saving_category="gifts")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Ride a bike to work", social=True, ds_suggested=True, difficulty="medium", description="Got a bike?  Use it for a week or a month to get to work, get in shape, and give the cost savings to charity.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="transport")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Run to work", social=True, ds_suggested=True, difficulty="medium", description="Is work close enough to run home?  Then do it.  You'll get diesel, and the charity will get your transportation costs.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="transport")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Sneak a flask into a bar", social=True, ds_suggested=False, difficulty="medium", description="Bars are expensive, but highly necessary.  Take a flask with you, and donate your drink savings.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="entertain")
    saving.saving_categories.add(category)
    saving.save()
    category = SavingCategory.objects.get(saving_category="foodbev")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="No appetizers", social=True, ds_suggested=True, difficulty="easy", description="If you're an app eater, give it up for one dinner (or eat it at home) and donate your savings. Added bonus: better prepares you for swimsuit season.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="foodbev")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Pre-gaming!!!", social=True, ds_suggested=False, difficulty="easy", description="Pre-gaming rocks.  Do it at home and save some flow.  That's right, you get to party and save lives.  Win-win (until the next morning).")
    saving.save()
    category = SavingCategory.objects.get(saving_category="entertain")
    saving.saving_categories.add(category)
    saving.save()
    category = SavingCategory.objects.get(saving_category="foodbev")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Volunteer as DD for the night", social=False, ds_suggested=True, difficulty="medium", description="Volunteer as a designated driver for a night and donate your typical bar tab to charity.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="entertain")
    saving.saving_categories.add(category)
    saving.save()
    category = SavingCategory.objects.get(saving_category="foodbev")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="House-party Fridays", social=True, ds_suggested=True, difficulty="hard", description="Face it: house parties are funner than bars. Throw a Friday night house party for your friends. Their admission price is a $20 donation to charity.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="entertain")
    saving.saving_categories.add(category)
    saving.save()
    category = SavingCategory.objects.get(saving_category="foodbev")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Cheap date", social=False, ds_suggested=False, difficulty="hard", description="This is a great high-maintenance filter. Discover if you have a good date by taking her on a picnic, cooking a meal at home, or a cheap but awesome burger joint, and donating the savings.  Good luck!")
    saving.save()
    category = SavingCategory.objects.get(saving_category="entertain")
    saving.saving_categories.add(category)
    saving.save()
    category = SavingCategory.objects.get(saving_category="foodbev")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Buy generics", social=False, ds_suggested=True, difficulty="easy", description="Generic products are basically the same except for the packaging, so you're not really giving anything up.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="shopping")
    saving.saving_categories.add(category)
    saving.save()
    category = SavingCategory.objects.get(saving_category="home")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="No window shopping", social=False, ds_suggested=False, difficulty="medium", description="Shopaholic? Give it a rest for a month.  Figure out what you usually spend on casual shopping trips and donate it instead.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="shopping")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="No bottled water", social=False, ds_suggested=True, difficulty="easy", description="C'mon. This is an easy one.  Just drink tap water instead of bottled water.  It's everywhere and just as good as the bottled stuff.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="foodbev")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Home brew", social=False, ds_suggested=True, difficulty="easy", description="Store-bought coffee is anywhere from expensive to really expensive. Don't give up the caffeine fix, just give up the expensive stuff and make your own at home or the office.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="foodbev")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Grow a beard with a good excuse", social=True, ds_suggested=True, difficulty="medium", description="Razors are expensive, so take a break from shaving and donate the cost of your razors.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="other")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Pot luck dinner", social=True, ds_suggested=True, difficulty="medium", description="Instead of going out to a restaurant to eat, host a potluck dinner at your place and have everyone donate $25 to a charity of your choice.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="entertain")
    saving.saving_categories.add(category)
    saving.save()
    category = SavingCategory.objects.get(saving_category="foodbev")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Brown bag lunch", social=False, ds_suggested=True, difficulty="easy", description="Make your lunch at home and bring it to work.  Doesn't have to be everyday.  Maybe just once a week. Save a bunch of dough.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="foodbev")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Replace texting plans with free texting apps", social=False, ds_suggested=True, difficulty="medium", description="Texting plans are absurdly expensive, and there are a ton of free texting apps out there.  Start using a free app for your most frequent contacts, reduce your texting plan, and donate the savings.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="tech")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Base cell phone plan", social=False, ds_suggested=True, difficulty="medium", description="See if you can reduce the number of cell phone minutes you use, downsize your plan, and donate the savings.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="tech")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Go snack free", social=False, ds_suggested=True, difficulty="easy", description="Resist an afternoon snack.  Donate it to charity instead.  Free byproduct: a little more health!")
    saving.save()
    category = SavingCategory.objects.get(saving_category="foodbev")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Join the library and borrow a book", social=False, ds_suggested=True, difficulty="medium", description="Buy a lot of books? Why not go old-fashioned with it and borrow them for free/cheap from a library?")
    saving.save()
    category = SavingCategory.objects.get(saving_category="entertain")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Cancel one mag/newspaper subscription", social=False, ds_suggested=True, difficulty="easy", description="Everybody's got a subscription to at least one magazine or newspaper they don't read.  Cancel one and donate your savings.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="entertain")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="$5 spending limit all week", social=True, ds_suggested=False, difficulty="hard", description="See if you can go an entire week without spending more than $5 on a single item, except maybe groceries. We (almost) guarantee it will save you a lot of dough.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="shopping")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Public transport only", social=False, ds_suggested=True, difficulty="medium", description="Public transportation is awesome because driving is annoying and cabs are expensive. Why not spend a week getting around only by public transportation? Pretend the driver is your chauffeur if you like.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="transport")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="No A/C", social=False, ds_suggested=True, difficulty="medium", description="Calling anybone bold enough to do it: turn off the A/C for a week or month this summer.  That sucker is a money-eater and an easy target for saving money.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="home")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Set up auto bill pay", social=False, ds_suggested=True, difficulty="easy", description="Do you get hit with late fees on bills even though you have enough money to pay them? Time to set up auto bill pay and not let it happen again.  Then you can donate the amount you paid in late fees last year.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="finance")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Give up a haircut", social=False, ds_suggested=True, difficulty="easy", description="Just skip your next haircut and donate the normal cost of it.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="other")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Free credit scores...really", social=False, ds_suggested=True, difficulty="easy", description="Do you pay a lot to get your credit scores?  Did you know Credit Karma will hook you up with a credit score for free?  Use it, and donate what you used to pay to some of the other services.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="finance")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Pay down credit card debt", social=False, ds_suggested=True, difficulty="easy", description="In case you need more of an incentive to stop paying interest on your credit card balance, pay it down and donate a year's worth of your interest savings.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="finance")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Leave the plastic at home", social=False, ds_suggested=True, difficulty="hard", description="Going cash only may seem like a bad bet, but it can actually save you a lot.  It's tough to put a price on it, but I'll bet you'll save at least $20 a week by keeping your cards at home.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="finance")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Credit card bill exam", social=False, ds_suggested=True, difficulty="medium", description="Go through the last 12 months of your credit card bill and cancel any auto-subscriptions you no longer use.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="finance")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="No credit card fees", social=False, ds_suggested=True, difficulty="medium", description="Transfer to a no annual fee credit card.  The rewards are rarely worth the cost.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="finance")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Free moving boxes", social=False, ds_suggested=True, difficulty="medium", description="Are you moving?  Boxes are crazy expensive.  But there are a lot of ways to get them for free.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="home")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Shop for new car insurance", social=False, ds_suggested=True, difficulty="medium", description="Go shop around for car insurance. Insurance companies like new customers, so chances are good that you can find the same policy at a cheaper rate.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="finance")
    saving.saving_categories.add(category)
    saving.save()
    category = SavingCategory.objects.get(saving_category="transport")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Eat, then grovery shop", social=False, ds_suggested=True, difficulty="easy", description="Stop grocery shopping when you're hungry.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="foodbev")
    saving.saving_categories.add(category)
    saving.save()
    category = SavingCategory.objects.get(saving_category="shopping")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Breakfast at home", social=False, ds_suggested=True, difficulty="easy", description="If you buy your breakfast every morning, you can save a small sum by making it at home.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="foodbev")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Start couponing", social=False, ds_suggested=True, difficulty="medium", description="Couponing is super easy these days, thanks to the cyberwebs.  Make sure that when you use coupons, they're only for items you would have bought anyway.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="foodbev")
    saving.saving_categories.add(category)
    saving.save()
    category = SavingCategory.objects.get(saving_category="shopping")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Donate your rewards", social=False, ds_suggested=True, difficulty="easy", description="If you're a member of any store loyalty programs or credit card rewards programs, donate your year-end cash rewards to charity.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="shopping")
    saving.saving_categories.add(category)
    saving.save()
    category = SavingCategory.objects.get(saving_category="finance")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Buy used stuff", social=False, ds_suggested=True, difficulty="medium", description="About to make a big purchase?  Consider buying new instead of used.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="shopping")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Put off car purchase for one year", social=False, ds_suggested=False, difficulty="hard", description="In the market for a car?  Hold off, and put that money to better use.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="transport")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Get a much cheaper car than you intended", social=False, ds_suggested=True, difficulty="hard", description="Donate the savings to charity.  We'll send you a bumper sticker.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="transport")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Move into a smaller home", social=False, ds_suggested=True, difficulty="hard", description="Perhaps the hardest Downsize possible.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="home")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="No dessert", social=True, ds_suggested=True, difficulty="easy", description="If you're a dessert eater, do your heart and your favorite charity a favor by avoiding dessert.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="foodbev")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Hang dry clothes", social=False, ds_suggested=True, difficulty="hard", description="Ever want to annoy your nit-picky neighbors for a good cause?  Here's your chance.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="home")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Dedicate one night a week to cooking", social=False, ds_suggested=True, difficulty="medium", description="For those that eat out every night, time to learn to cook.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="foodbev")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Sell old gadgets and electronics", social=False, ds_suggested=True, difficulty="medium", description="Believe it or not, that Palm Pilot is worth something.  Clean out your closet, sell them online and donate your proceeds.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="tech")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Don't buy lotto tickets", social=False, ds_suggested=True, difficulty="easy", description="You're not going to win.  Donate your money instead.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="shopping")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Cable TV reduction", social=False, ds_suggested=True, difficulty="easy", description="Bet you can get rid of some of those premium channels you never watch, especially now with a lot of the good stuff being accessible online.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="entertain")
    saving.saving_categories.add(category)
    saving.save()
    category = SavingCategory.objects.get(saving_category="tech")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="No more cable/satellite TV", social=False, ds_suggested=True, difficulty="hard", description="Say goodbye to cable, and only rely on DVDs and online streaming.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="entertain")
    saving.saving_categories.add(category)
    saving.save()
    category = SavingCategory.objects.get(saving_category="tech")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="AOL: switch off your account", social=False, ds_suggested=False, difficulty="medium", description="There are still about 5 million paid subscribers to AOL. Please stop.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="tech")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Drop your landline", social=False, ds_suggested=True, difficulty="medium", description="If you get good cell reception in your house, consider dropping your landline as long as it doesn't mean you have to increase your cell phone minutes.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="tech")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Rent your stuff", social=False, ds_suggested=True, difficulty="medium", description="Your car, a spare room, your equipment, your tools... just about everything can be rented these days, which should give you some cash you can donate.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="home")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Negotiate a discount", social=False, ds_suggested=True, difficulty="medium", description="(Almost) everything is negotiable, even in America. Negotiate something down from the sticker price and donate the difference.  Negotiating is also a great skill to have and is pretty fun too.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="shopping")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Go dry", social=True, ds_suggested=True, difficulty="hard", description="How long can you do it for charity?  A day, week, month, maybe even longer?  To state the obvious, you'll save a ton doing this.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="foodbev")
    saving.saving_categories.add(category)
    saving.save()
    category = SavingCategory.objects.get(saving_category="entertain")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Custom-made jewelry", social=False, ds_suggested=True, difficulty="hard", description="Expensive jewelry is one of those weird markets where you can usually pay much less for something you customized, instead of buying in-store.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="shopping")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Don't check bags on flight", social=False, ds_suggested=True, difficulty="medium", description="You're not going to wear all of that.  Pack less stuff, put it in the overhead, and donate the checked bag fees instead.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="transport")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Bring snack with you on plane", social=False, ds_suggested=True, difficulty="easy", description="You know you're going to want a snack on the plane.  Just bring it with you to the airport.  It will taste better than that pound of generic trail mix.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="transport")
    saving.saving_categories.add(category)
    saving.save()
    category = SavingCategory.objects.get(saving_category="foodbev")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Split a cab", social=True, ds_suggested=True, difficulty="easy", description="Have to take a cab somewhere (like to/from the airport)? Find somebody to split it with.  You might even make a friend out of it.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="transport")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Sneak food into stadium, concert, movie", social=False, ds_suggested=False, difficulty="easy", description="Do stadium or theater prices make you mad?  Buy your snack before you get inside, and donate the money to a good cause instead.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="entertain")
    saving.saving_categories.add(category)
    saving.save()
    category = SavingCategory.objects.get(saving_category="foodbev")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Go 3 or 4 wears in between dry cleaning", social=False, ds_suggested=True, difficulty="medium", description="Dry cleaning is expensive.  See if you can stretch your number of wears between dry cleaning.  This is going to require the right balance of savings vs. dirt-baggery.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="home")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Don't buy items near the register", social=False, ds_suggested=True, difficulty="easy", description="We all get sucked into buying a thing or two at the register, even though it's definitely not on our shopping list.  Make a pact not to do that for a month.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="shopping")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="BYOB restaurant night", social=True, ds_suggested=True, difficulty="medium", description="Get a crew together, head to a BYOB restaurant with your own bottles, and donate the savings to charity.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="foodbev")
    saving.saving_categories.add(category)
    saving.save()
    category = SavingCategory.objects.get(saving_category="entertain")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Cheaper bottle of wine", social=True, ds_suggested=True, difficulty="medium", description="Let's see if you can talk your dinner table out of buying the expensive bottle, and instead buy a cheaper bottle and donate the difference.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="foodbev")
    saving.saving_categories.add(category)
    saving.save()
    category = SavingCategory.objects.get(saving_category="entertain")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Doggy bag meals", social=False, ds_suggested=True, difficulty="easy", description="Didn't eat everything on your plate?  Get the waiter to wrap it up for you and eat the leftovers for lunch.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="foodbev")
    saving.saving_categories.add(category)
    saving.save()
    category = SavingCategory.objects.get(saving_category="entertain")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Food truck dinner (do they even serve dinner?", social=True, ds_suggested=True, difficulty="medium", description="Food trucks are popping up everywhere, and they're usually delicious and cheap.  See if you can convince someone to hit a food truck with you instead of the restaurant, and donate the savings.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="foodbev")
    saving.saving_categories.add(category)
    saving.save()
    category = SavingCategory.objects.get(saving_category="entertain")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Drop or add degree on the thermostat", social=False, ds_suggested=True, difficulty="easy", description="What's a degree worth?  Kind of a lot, actually.  Drop one degree in winter or add one degree in summer.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="home")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Booze-free on airplane", social=False, ds_suggested=True, difficulty="easy", description="Skip the booze on your next airplane trip, and donate the cost of that mini bottle to charity.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="foodbev")
    saving.saving_categories.add(category)
    saving.save()
    category = SavingCategory.objects.get(saving_category="transport")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Buy nose-bleed tix and give to special olympics", social=True, ds_suggested=True, difficulty="easy", description="Don't skip the game, but just downsize your tickets a little bit.  Besides, the best fans are rarely in the good seats.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="entertain")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Buy cheapest airline ticket available", social=False, ds_suggested=True, difficulty="medium", description="Tons of ways to do downsize plane tickets: go economy if you're a business flier, do a layover instead of non-stop, pick a less desirable time, a less convenient airport, a smaller airline, etc.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="transport")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Newspaper gift wrap", social=False, ds_suggested=True, difficulty="easy", description="Newspaper, reusable boxes/bags, etc.  Figure out a way to wrap a present without having to buy gift wrap.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="gifts")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="E-card", social=False, ds_suggested=True, difficulty="easy", description="It's easier, cheaper and more fun.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="gifts")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Carpool", social=True, ds_suggested=True, difficulty="medium", description="Do you usually drive yourself to work or school?  Coordinate with a friend (or even a stranger), travel together, and each person can split the gas costs.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="transport")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Cheaper dish", social=True, ds_suggested=True, difficulty="easy", description="Find what entree you want the most, then order the cheapest one on the menu and donate the difference.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="foodbev")
    saving.saving_categories.add(category)
    saving.save()
    category = SavingCategory.objects.get(saving_category="entertain")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Volunteer for friends", social=True, ds_suggested=True, difficulty="medium", description="Got a project requiring manual labor?  Ask your friends to volunteer to help you (e.g. move, paint a house, etc.) and in exchange you donate an hourly rate to their favorite cause. Make a party out of it, if you're into that kind of thing.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="home")
    saving.saving_categories.add(category)
    saving.save()
    saving = Saving(saving_type="Boycott for charity", social=True, ds_suggested=False, difficulty="medium", description="Got beef with a company that wronged you?  Start a mini-boycott of their products and donate what you would have spent on their stuff to charity. If you're really angry, get some friends to join in on the fun.")
    saving.save()
    category = SavingCategory.objects.get(saving_category="shopping")
    saving.saving_categories.add(category)
    saving.save()
    category = SavingCategory.objects.get(saving_category="other")
    saving.saving_categories.add(category)
    saving.save()
